console.log(Math.PI);
console.log(Math.E);
console.log(Math.round(4.7));
let x = 5.6;
let y = 3.2;
let a = 7;
let z;
z = Math.round(x);
console.log(z); 
z = Math.round(y);
console.log(z);
z = Math.floor(x);
console.log(z);
z = Math.floor(y);
console.log(z);
z = Math.ceil(x);
console.log(z);
z = Math.ceil(y);
console.log(z);
z = Math.trunc(x);
console.log(z);
z = Math.trunc(y);
console.log(z);
z = Math.pow(x, y);
console.log(z);
z = Math.sqrt(x);
console.log(z);
z = Math.sqrt(y);
console.log(z);
z = Math.abs(x);
console.log(z);
let max = Math.max(x, y, a);
console.log(max);
let min = Math.min(x, y, a);
console.log(min);